In [3]:
import numpy as np


1.Array Creation


Create a 1-dimensional array of integers from 1 to 10.

In [4]:
a=np.array(range(1,11))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a 2-dimensional array with random float values of shape (3, 4).

In [7]:
a=np.random.rand(3,4)
a

array([[0.2569908 , 0.2479606 , 0.72453459, 0.6140947 ],
       [0.26580091, 0.21419366, 0.54590826, 0.14666763],
       [0.30467581, 0.11453549, 0.66462492, 0.59844891]])

Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [9]:
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Array Operations:

Given two 1-dimensional arrays, perform element-wise addition,
subtraction, multiplication, and division.

In [13]:
a=np.array([1,4,7])
b=np.array([2,3,5])
c=a+b
d=b-a
e=b*a
f=a/b
print(c)
print(d)
print(e)
print(f)

[ 3  7 12]
[ 1 -1 -2]
[ 2 12 35]
[0.5        1.33333333 1.4       ]


Calculate the mean, median, and standard deviation of a given 1-
dimensional array.

In [15]:
a=np.array([4,5,6,7,8])
b=np.mean(a)
c=np.median(a)
d=np.std(a)
print(b)
print(c)
print(d)

6.0
6.0
1.4142135623730951


Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [18]:
a=np.array(range(1,13))
a.reshape(3,4)
           

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Array Indexing and Slicing:

Extract the first row and last column of a 2-dimensional array.

In [23]:
a=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a[0])
print(a[:,-1])


[4 5 6]
[6 9 3]


Reverse the order of elements in a 1-dimensional array.

In [25]:
a=np.array([4,5,6,7,8])
print(a[::-1])

[8 7 6 5 4]


Select elements from a 2-dimensional array that satisfy a specific
condition (e.g., values greater than a certain threshold).

In [26]:
a=np.array([[4,5,6],[7,8,9],[1,2,3]])
b=[x for x in a.flatten() if x%2==0]
b

[4, 6, 8, 2]

Array Broadcasting:

Add a scalar value to each element of a 2-dimensional array.

In [28]:
a=np.array([[4,5,6],[7,8,9],[1,2,3]])
b=a+4
b

array([[ 8,  9, 10],
       [11, 12, 13],
       [ 5,  6,  7]])

Multiply a 1-dimensional array with a 2-dimensional array, leveraging
NumPy's broadcasting rules.

In [30]:
a=np.array([[4,5,6],[7,8,9],[1,2,3]])
b=np.array([2,3,5])
c=a*b
c

array([[ 8, 15, 30],
       [14, 24, 45],
       [ 2,  6, 15]])

Linear Algebra:

Calculate the dot product of two 1-dimensional arrays.

In [33]:
b=np.array([[2,3],[3,4]])
a=np.array([[1,4],[2,3]])
a.dot(b)

array([[14, 19],
       [13, 18]])

Compute the matrix multiplication of two 2-dimensional arrays.

In [35]:
np.matmul(a,b)

array([[14, 19],
       [13, 18]])

Find the inverse and determinant of a square matrix.

In [6]:
import numpy as np 

In [8]:
a=np.array([[1,4],[2,3]])

In [9]:
d=np.linalg.det(a)
d

-5.000000000000001

In [10]:
c=np.linalg.inv(a)
c

array([[-0.6,  0.8],
       [ 0.4, -0.2]])